import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
// Official beUI source is not React Compiler transformed. Keep compiler migration
// diagnostics visible as warnings, while all application code retains strict defaults.
const beuiFiles = [
  "components/motion/theme-toggle.tsx",
  "components/motion/action-swap.tsx",
  "components/motion/animated-sidebar.tsx",
  "components/motion/shared-layout-bg.tsx",
  "lib/ease.ts",
  "components/motion/button/base.tsx",
  "lib/hooks/use-hover-capable.ts",
  "components/motion/input.tsx",
  "components/motion/tabs.tsx",
  "components/motion/table/index.tsx",
  "components/motion/table/editable-cell.tsx",
  "components/motion/table/row-handle.tsx",
  "components/motion/table/skeleton-rows.tsx",
  "components/motion/table/table-header.tsx",
  "components/motion/table/types.ts",
  "components/motion/table/use-column-reorder.ts",
  "components/motion/table/use-column-resize.ts",
  "components/motion/table/use-column-sort.ts",
  "components/motion/table/use-row-selection.ts",
  "components/motion/table/utils.ts",
  "components/motion/checkbox.tsx",
  "components/motion/table/table-menu.tsx",
  "lib/touch.ts",
  "components/motion/animated-badge.tsx",
  "components/motion/loader.tsx",
  "components/agents/prompt-input.tsx",
  "components/motion/button/index.tsx",
  "components/motion/popover-morph.tsx",
  "components/motion/select.tsx",
  "components/motion/button/magnetic.tsx",
  "components/motion/button/metallic.tsx",
  "components/motion/button/stateful.tsx",
  "components/motion/popover-position.ts",
  "components/motion/magnetic.tsx",
  "components/agents/message.tsx",
  "components/agents/message-bubble.tsx",
  "components/agents/message-context.tsx",
  "components/agents/message-scroller.tsx",
  "components/motion/preview-rail.tsx",
  "lib/hooks/use-dismiss.ts",
  "lib/hooks/use-hover-gesture.ts",
  "lib/hooks/use-tap-gesture.ts",
  "components/agents/approval-card/index.tsx",
  "components/agents/approval-card/types.ts",
  "components/agents/agent-disclosure.tsx",
  "components/motion/action-swap-roll.tsx",
  "components/motion/radio.tsx",
  "components/motion/action-swap.tsx",
  "components/motion/command-palette.tsx",
  "lib/hooks/use-on-open.ts",
  "lib/hooks/use-row-cursor.ts",
  "lib/hooks/use-touch-capable.ts",
  "lib/presence-gate.tsx"
];
export default defineConfig([...nextVitals, ...nextTs,
  { files: beuiFiles, rules: {
    "react-hooks/refs": "warn",
    "react-hooks/immutability": "warn",
    "react-hooks/set-state-in-effect": "warn",
  } },
  globalIgnores([".next/**", "generated/**", "next-env.d.ts", "playwright-report/**", "test-results/**"])]);
